package com.yanamobility.usblibrary.Utils;

public enum RX {
    SIG_ARC_MAIA_DISPLAY1,
    SIG_PB4_STS,
    SIG_PB1_STS,
    SIG_PB2_STS,
    SIG_PB3_STS,
    SIG_ACTIVITY_ID_FEEDBACK,
    SIG_AIDU_STS,
    SIG_CBU_DIAGREQDYNA,
    SIG_DIRECTION_OF_SPEECH,
    SIG_MUSIC,
    SIG_MSG_RECEIVED,
    SIG_LOOK_LEFT_RIGHT,
    SIG_CLICK_SELFIE,
    SIG_CALL,
    SIG_VEHICLE_SPEED_ESC12,
    SIG_STS_NAV_ROUTE,
    SIG_AUTO_RAIN,
    SIG_STS_RKE,
    SIG_STS_IGN,
    SIG_STS_DOOR,
    SIG_AC_SWT_STS,
    SIG_ENG_SPD,
    SIG_STS_ENG,
    SIG_STS_AC_COMPRESSOR,
    SIG_ENG_TEMP
}
